# Generated by Django 2.2.2 on 2019-06-17 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pair_tickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
